
name: buildDocker

on:
 push:
   branches: "main"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/findnseek:latest 

      -         
        name: connect ssh
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker stop ${{ secrets.CNAME }}
            docker rm ${{ secrets.CNAME }}
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/findnseek
            docker run --name ${{ secrets.CNAME }} -p -d 8000:8000 ${{ secrets.DOCKERHUB_USERNAME }}/findnseek                 
